name: Manual Build Firmware
on:
  workflow_dispatch:
    inputs:
      pio_env:
        description: 'PIO环境名称'
        required: true
        default: 'esp32-diy-v1'
      build_flags:
        description: '自定义编译参数'
        required: false
        default: '-DBATTERY_PIN=35 -DADC_MULTIPLIER=1.85 -DADC_ATTENUATION=ADC_ATTEN_DB_11 -DBUTTON_PIN=39'

jobs:
  build:
    uses: ./.github/workflows/build_firmware.yml
    with:
      pio_env: ${{ github.event.inputs.pio_env }}
      build_flags: ${{ github.event.inputs.build_flags }}
